# Generated by Django 5.1.1 on 2024-10-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.IntegerField(default=0, primary_key='True', serialize=False)),
                ('user_id', models.CharField(default='null', max_length=150)),
                ('product_id', models.CharField(default='null', max_length=150)),
                ('quality', models.FloatField(default=0.0, max_length=50)),
                ('rate', models.FloatField(default=0.0, max_length=50)),
                ('ammount', models.FloatField(default=0.0, max_length=50)),
                ('cr_date', models.DateField(default=0)),
            ],
        ),
    ]
