# Generated by Django 5.1.1 on 2024-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_product_id_alter_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default='null'),
        ),
    ]
