# Generated by Django 5.1.1 on 2024-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('product_description', models.CharField(default='null', max_length=150)),
                ('product_type', models.CharField(default='null', max_length=150)),
                ('price', models.FloatField(default=0.0, max_length=50)),
                ('discount', models.FloatField(default=0.0, max_length=50)),
                ('gst', models.FloatField(default=0.0, max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
